#
# BTstack example 'a2dp_sink_demo' for ESP32 port
#
# Generated by /home/ava/repos/wireless/esp/btstack/port/esp32
# On Mon Mar 20 19:42:04 2023

PROJECT_NAME := spoofing

include $(IDF_PATH)/make/project.mk
